Eventos/Eventos/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Eventos.Models
{
    public class Event
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Place { get; set; }
        public string TypeEvent { get; set; }
        public DateTime? DayEvent { get; set; }
        public string Capacity { get; set; }
        public int CityId { get; set; }
        [ForeignKey("CityId")]
        public City City { get; set; }


    }
}

Eventos/Eventos/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eventos.Models;

namespace Eventos.Controllers
{
    public class CitiesController : Controller
    {
        private EventDbContext db = new EventDbContext();

        // GET: Cities
        public ActionResult Index()
        {
            return View(db.Citys.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Citys.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,PostalCode")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Citys.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Citys.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PostalCode")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Citys.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Citys.Find(id);
            db.Citys.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eventos/Eventos/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eventos.Models;

namespace Eventos.Controllers
{
    public class EventsController : Controller
    {
        private EventDbContext db = new EventDbContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            ViewBag.Ciudades = (from c in db.Citys
                                select c).ToList();
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Place,TypeEvent,DayEvent,Capacity,CityId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityId = new SelectList(db.Citys, "Id", "Name", "PostalCode", @event.CityId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eventos/Eventos/Views/Events/Create.cshtml
@model Eventos.Models.Event

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row" >
        <h4 class="display-4 ">Eventos</h4>
        <hr />
        
    </div>

    <div class="form-horizontal col-md-5 border border-info rounded  text-black " style="background-color:#9db4f5"  >

        <div class="form-group  " style="margin-left:50px;">


            <div class="form-group ">
                <label for="" class="col-md-5 col-form-label">Titulo</label>
                <div class="col-md-10 ">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="" class="col-md-5 col-form-label">Lugar</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="" class="col-md-5 col-form-label">Tipo de evento</label>
                <div class="col-md-10">

                    <select name="TypeEvent" class="form-control">
                        <option value="value">Elige un tipo</option>
                        <option>Familiar</option>
                        <option>Adultos</option>
                        <option>Infantil</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="" class="col-md-5 col-form-label">Dia del evento</label>
                <div class="col-md-10">
                    <input type="date" name="DayEvent" value="" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label for="" class="col-md-5 col-form-label">Capacidad</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-6  ">Selecciona una ciudad</label>
                <div class="col-md-10 ">
                    <select name="CityId" class="form-control">
                        <option>Elige una Ciudad</option>
                        @foreach (var item in ViewBag.Ciudades)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="justify-content-center col-md-5" style="margin-left:100px;">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "Cities")" class=" text-white btn  btn-danger" style="margin-left:20px; margin-top:10px;">Regresar</a>

</div>

<br>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eventos/Eventos/Views/Events/Delete.cshtml
@model Eventos.Models.Event

@{
    ViewBag.Title = "Delete";
}

    <h2 class="display-4">Eliminar</h2>


<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt class="lead">
            Titulo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt class="lead">
            Lugar
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>

        <dt class="lead">
            Tipo de evento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeEvent)
        </dd>

        <dt class="lead">
            Dia del evento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayEvent)
        </dd>

        <dt class="lead">
            Capacidad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <h6 class="font-weight-bold">Estas seguro de eliminar tu evento?</h6>
<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> 
    <a href="@Url.Action("Index", "Events")" class=" text-white btn  btn-dark" style="margin-left:20px;">Regresar</a>

</div>
    }
</div>

Eventos/Eventos/Views/Events/Details.cshtml
@model Eventos.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2 class="display-4">Detalles</h2>

<div class="form-group">

    <hr />
    <dl class="dl-horizontal">
        <dt class="lead">
            Titulo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt class="lead">
            Lugar
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>

        <dt class="lead">
            Tipo de evento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeEvent)
        </dd>

        <dt class="lead">
            Dia del evento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayEvent)
        </dd>

        <dt class="lead">
            Capacidad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

    </dl>
    <br />
    <a href="@Url.Action("Edit", "Events", new { id = Model.Id })" class=" text-white btn btn-warning">Editar</a>
    <a href="@Url.Action("Index", "Events")" class=" text-white btn  btn-danger" style="margin-left:20px;">Regresar</a>
    <br />

</div>

Eventos/Eventos/Views/Events/Edit.cshtml
@model Eventos.Models.Event

@{
    ViewBag.Title = "Edit";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-5">
        <h2 class="display-4">Editar</h2>
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <label for="" class="col-md-5 col-form-label">Titulo</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="" class="col-md-5 col-form-label">Lugar</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="" class="col-md-5 col-form-label">Tipo de evento</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TypeEvent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TypeEvent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="" class="col-md-5 col-form-label">Dia del evento</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DayEvent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DayEvent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="" class="col-md-5 col-form-label">Capacidad</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-warning text-white" />        
            <a href="@Url.Action("Index", "Events")" class=" text-white btn btn-danger" style="margin-left:20px;">Regresar</a>

        </div> 
    </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eventos/Eventos/Views/Events/Index.cshtml
@model IEnumerable<Eventos.Models.Event>

@{
    ViewBag.Title = "Index";
}
<br />
<p>
    <a href="@Url.Action("Create", "Events")" class="btn- btn btn-success">Nuevo evento</a>

</p>
<div class="row justify-content-center ">
    <div class="col-md-11">
        <div class="card m-2">
            <div class="card-header py-2 bg-secondary">
                <h4 class="text-center text-white">Lista de Eventos</h4>
            </div>
            <div class="card-body">
                <table class="table table-hover table-sm">
                    <tr>
                        <th>
                            Titulo
                        </th>
                        <th>
                            Lugar
                        </th>
                        <th>
                            Tipo de evento
                        </th>
                        <th>
                            Dia del evento
                        </th>
                        <th>
                            Capacidad
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Place)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TypeEvent)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DayEvent)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Capacity)
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", "Events", new { id = item.Id })" class="text-warning"><i class="fas fa-edit"></i> </a> |
                                <a href="@Url.Action("Details", "Events", new { id = item.Id })" class="text-info"><i class="fas fa-info-circle"></i></a> |
                                <a href="@Url.Action("Delete", "Evetns", new { id = item.Id })" class="text-danger"><i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>